import {
  access,
  add,
  alert,
  auditForwarded,
  calendar,
  calendarAttention,
  calendarMoney,
  check,
  checkSolid,
  clockSolid,
  close,
  closeSolid,
  condominium,
  config,
  doc,
  docCheck,
  docX,
  docWarning,
  attention,
  attentionSolid,
  attentionRounded,
  expand,
  filter,
  headphone,
  info,
  infoSolid,
  left2,
  left3,
  localization,
  motorcycle,
  dotsVertical,
  out,
  pencil,
  plusSolid,
  helpCircle,
  refresh,
  right2,
  right3,
  sandwich,
  search,
  down2,
  up2,
  starSolid,
  onu,
  sub,
  tecnico,
  trash,
  users,
  user,
  clock,
  clockWarning,
  working,
  checkOutlined,
  download,
  upload,
  condominium2,
  activeDeactivate,
  addTelephone,
  addUser,
  alarmClockCheck,
  alarmClockMinus,
  alarmClockPlus,
  alarmClockOff,
  alarmClock,
  alertTelephone,
  alertUser,
  announcement,
  bankNote,
  award,
  award2,
  bank,
  barChartSquareDown,
  barChartSquareMinus,
  barChartSquarePlus,
  barChartSquareUp,
  barCode,
  batteryCharging,
  bellOff,
  bellRinging,
  bookOpen,
  boxBlock,
  boxClock,
  boxLeft,
  boxMinus,
  boxPin,
  boxPlus,
  boxSearch,
  boxX,
  calendarAdd,
  calendarBlock,
  calendarCheck,
  calendarMarker,
  calendarReserved,
  calendarX,
  cameraOff,
  priority,
  listCheck,
  checkUser,
  checkVerified,
  clipboardAlert,
  clipboardCheck,
  clipboardLocalization,
  clipboardPlus,
  clipboardX,
  clockPlus,
  clockStopwatch,
  closeRounded,
  cloudDownload,
  cloudUpload,
  coinsHand,
  comeIn,
  creditCardCheck,
  creditCardLock,
  creditCardPlus,
  creditCardShield,
  creditCardX,
  creditCard,
  docPlus,
  docBar,
  docDownload,
  docEmpty,
  docGraphic,
  docQuestion,
  docSearch,
  faceFrown,
  faceHappy,
  faceId,
  faceNeutral,
  faceSad,
  faceSmile,
  fastBackward,
  fastForward,
  fileLock,
  fileShield,
  heartHand,
  homeCheck,
  home,
  homeDown,
  homeLocalization,
  homeUp,
  homeUpdate,
  homeX,
  horizontalBarChart,
  imageCheck,
  imageDown,
  imageLeft,
  imagePlus,
  imageRight,
  imageUp,
  imageX,
  layoutAlt,
  layoutBottom,
  layoutGrid,
  layoutGrid2,
  layoutLeft,
  layoutRight,
  lineChartDown,
  lineChartUp,
  linkBroken,
  listX,
  lockUnlocked,
  markerPin,
  messageAlert,
  messageChat,
  messageCheck,
  messageHeart,
  messagePlus,
  messageQuestionCircle,
  messageText,
  messageX,
  microphoneOff,
  moduleBox,
  module,
  negotiationBlock,
  orderBottom,
  orderGeneric,
  orderLetter1,
  orderLetter2,
  numberOrdererDecrescent,
  numberOrdererCrescent,
  orderUp,
  phoneBlock,
  phoneCall,
  phoneCall2,
  phoneHangUp,
  phoneIncoming,
  phoneOutgoing,
  phoneOutgoing1,
  phonePause,
  presentationChart,
  receiptCheck,
  receiveTelephone,
  listPlus,
  removeTelephone,
  removeUser,
  searchLocalization,
  shieldOff,
  shieldTick,
  shoppingCart,
  stop,
  tagDivision,
  thumbsDown,
  thumbsUp,
  timeTelephone,
  userBlock,
  userBottom,
  userClock,
  userLeft,
  userMarker,
  userMinus,
  userRight,
  userSearch,
  userTop,
  lockVerification,
  viewBlock,
  volumeMax,
  volumeMinus,
  volumePlus,
  volumeX,
  watchCircle,
  workBag,
  zapOff,
  zoomIn,
  zoomOut,
  block,
  box,
  boxCheck,
  boxDown,
  boxWarning,
  boxTop,
  business,
  camera,
  camera2,
  car,
  certificate,
  change,
  click,
  click2,
  clip,
  clipboard,
  cloud,
  comment,
  config2,
  convenient,
  coord,
  coordinate,
  copy,
  cto,
  cursor,
  database,
  diamond,
  divide,
  down,
  down3,
  fingerprint,
  flag,
  forwardedService,
  gift,
  globe1,
  globe2,
  graphic,
  graphic2,
  lineChart,
  group,
  hand,
  heart,
  historic,
  hook,
  horizontal,
  image,
  inbox,
  information,
  intersection,
  key,
  laptop,
  left,
  lightbulb,
  link,
  list,
  list2,
  mail,
  map,
  maximize,
  microphone,
  minimize,
  modem,
  money,
  monitor,
  dotsHorizontal,
  move,
  negotiation,
  netflix,
  notification,
  olt,
  passcode,
  pause,
  percent,
  photo,
  pin,
  pin2,
  pix,
  play,
  plus,
  printer,
  qrcode,
  radio,
  receipt,
  recording1,
  recording2,
  regions,
  repeat,
  restore,
  right,
  rota,
  sale,
  save,
  scan,
  lock,
  send,
  serial,
  server,
  share,
  shield,
  simcard,
  smartphone,
  speedometer,
  star,
  stb,
  submit,
  tag,
  target,
  target3,
  telephone,
  ticket,
  time,
  total,
  trophy,
  tv,
  up,
  up3,
  vertical,
  view,
  wallet,
  whatsapp,
  wifi,
  zap,
  linkExternal,
  lockPlus,
  listAlert,
  switchVertical2,
  switchVertical1,
  switchHorizontal2,
  edit2,
  process,
  clockCheck,
  switchHorizontal1,
  passcodeLock,
  delete as delete_,
} from './iconsText';

// To add an icon, use kebab-case on key name and insert only SVG paths on value
export const iconsPaths = {
  access,
  'active-deactivate': activeDeactivate,
  'add-telephone': addTelephone,
  'add-user': addUser,
  add,
  'alarm-clock-check': alarmClockCheck,
  'alarm-clock-minus': alarmClockMinus,
  'alarm-clock-off': alarmClockOff,
  'alarm-clock-plus': alarmClockPlus,
  'alarm-clock': alarmClock,
  'alert-telephone': alertTelephone,
  'alert-user': alertUser,
  alert,
  announcement,
  'attention-rounded': attentionRounded,
  'attention-solid': attentionSolid,
  attention,
  'audit-forwarded': auditForwarded,
  award,
  award2,
  'bank-note': bankNote,
  bank,
  'bar-chart-square-down': barChartSquareDown,
  'bar-chart-square-minus': barChartSquareMinus,
  'bar-chart-square-plus': barChartSquarePlus,
  'bar-chart-square-up': barChartSquareUp,
  'bar-code': barCode,
  'battery-charging': batteryCharging,
  'bell-off': bellOff,
  'bell-ringing': bellRinging,
  block,
  'book-open': bookOpen,
  'box-block': boxBlock,
  'box-check': boxCheck,
  'box-clock': boxClock,
  'box-down': boxDown,
  'box-left': boxLeft,
  'box-minus': boxMinus,
  'box-pin': boxPin,
  'box-plus': boxPlus,
  'box-search': boxSearch,
  'box-top': boxTop,
  'box-warning': boxWarning,
  'box-x': boxX,
  box,
  business,
  'calendar-add': calendarAdd,
  'calendar-attention': calendarAttention,
  'calendar-block': calendarBlock,
  'calendar-check': calendarCheck,
  'calendar-marker': calendarMarker,
  'calendar-money': calendarMoney,
  'calendar-reserved': calendarReserved,
  'calendar-x': calendarX,
  calendar,
  'camera-off': cameraOff,
  camera,
  camera2,
  car,
  certificate,
  change,
  'check-outlined': checkOutlined,
  'check-solid': checkSolid,
  'check-user': checkUser,
  'check-verified': checkVerified,
  check,
  click,
  click2,
  clip,
  'clipboard-alert': clipboardAlert,
  'clipboard-check': clipboardCheck,
  'clipboard-localization': clipboardLocalization,
  'clipboard-plus': clipboardPlus,
  'clipboard-x': clipboardX,
  clipboard,
  'clock-check': clockCheck,
  'clock-plus': clockPlus,
  'clock-solid': clockSolid,
  'clock-stopwatch': clockStopwatch,
  'close-rounded': closeRounded,
  'close-solid': closeSolid,
  'clock-warning': clockWarning,
  clock,
  close,
  'cloud-download': cloudDownload,
  'cloud-upload': cloudUpload,
  cloud,
  'coins-hand': coinsHand,
  'come-in': comeIn,
  comment,
  condominium,
  condominium2,
  config,
  config2,
  convenient,
  coord,
  coordinate,
  copy,
  'credit-card-check': creditCardCheck,
  'credit-card-lock': creditCardLock,
  'credit-card-plus': creditCardPlus,
  'credit-card-shield': creditCardShield,
  'credit-card-x': creditCardX,
  'credit-card': creditCard,
  cto,
  cursor,
  database,
  delete: delete_,
  diamond,
  divide,
  'doc-plus': docPlus,
  'doc-bar': docBar,
  'doc-check': docCheck,
  'doc-download': docDownload,
  'doc-empty': docEmpty,
  'doc-graphic': docGraphic,
  'doc-question': docQuestion,
  'doc-search': docSearch,
  'doc-warning': docWarning,
  'doc-x': docX,
  doc,
  down,
  down2,
  down3,
  download,
  edit2,
  expand,
  'face-frown': faceFrown,
  'face-happy': faceHappy,
  'face-id': faceId,
  'face-neutral': faceNeutral,
  'face-sad': faceSad,
  'face-smile': faceSmile,
  'fast-backward': fastBackward,
  'fast-forward': fastForward,
  'file-lock': fileLock,
  'file-shield': fileShield,
  filter,
  fingerprint,
  flag,
  'forwarded-service': forwardedService,
  gift,
  globe1,
  globe2,
  graphic,
  graphic2,
  group,
  hand,
  headphone,
  'heart-hand': heartHand,
  heart,
  historic,
  'home-check': homeCheck,
  'home-down': homeDown,
  'home-localization': homeLocalization,
  'home-up': homeUp,
  'home-update': homeUpdate,
  'home-x': homeX,
  home,
  hook,
  'horizontal-bar-chart': horizontalBarChart,
  horizontal,
  'image-check': imageCheck,
  'image-down': imageDown,
  'image-left': imageLeft,
  'image-plus': imagePlus,
  'image-right': imageRight,
  'image-up': imageUp,
  'image-x': imageX,
  image,
  inbox,
  'info-solid': infoSolid,
  info,
  information,
  intersection,
  key,
  laptop,
  'layout-alt': layoutAlt,
  'layout-bottom': layoutBottom,
  'layout-grid': layoutGrid,
  'layout-grid2': layoutGrid2,
  'layout-left': layoutLeft,
  'layout-right': layoutRight,
  left,
  left2,
  left3,
  lightbulb,
  'list-alert': listAlert,
  'line-chart-down': lineChartDown,
  'line-chart-up': lineChartUp,
  'line-chart': lineChart,
  'list-check': listCheck,
  'link-broken': linkBroken,
  'link-external': linkExternal,
  'list-plus': listPlus,
  'list-x': listX,
  list,
  list2,
  link,
  localization,
  'lock-plus': lockPlus,
  'lock-ulocked': lockUnlocked,
  'lock-verification': lockVerification,
  lock,
  mail,
  map,
  'marker-pin': markerPin,
  maximize,
  'message-alert': messageAlert,
  'message-chat': messageChat,
  'message-check': messageCheck,
  'message-heart': messageHeart,
  'message-plus': messagePlus,
  'message-question-circle': messageQuestionCircle,
  'message-text': messageText,
  'message-x': messageX,
  'microphone-off': microphoneOff,
  microphone,
  minimize,
  modem,
  'module-box': moduleBox,
  module,
  money,
  monitor,
  'dots-horizontal': dotsHorizontal,
  'dots-vertical': dotsVertical,
  motorcycle,
  move,
  'negotiation-block': negotiationBlock,
  negotiation,
  netflix,
  notification,
  'number-orderer-crescent': numberOrdererCrescent,
  'number-orderer-decrescent': numberOrdererDecrescent,
  olt,
  onu,
  'order-bottom': orderBottom,
  'order-generic': orderGeneric,
  'order-letter1': orderLetter1,
  'order-letter2': orderLetter2,
  'order-up': orderUp,
  out,
  'passcode-lock': passcodeLock,
  passcode,
  pause,
  pencil,
  percent,
  'phone-block': phoneBlock,
  'phone-call': phoneCall,
  'phone-call2': phoneCall2,
  'phone-hang-up': phoneHangUp,
  'phone-incoming': phoneIncoming,
  'phone-outgoing': phoneOutgoing,
  'phone-outgoing1': phoneOutgoing1,
  'phone-pause': phonePause,
  photo,
  pin,
  pin2,
  pix,
  play,
  'plus-solid': plusSolid,
  plus,
  'presentation-chart': presentationChart,
  printer,
  priority,
  process,
  qrcode,
  'help-circle': helpCircle,
  radio,
  'receipt-check': receiptCheck,
  receipt,
  'receive-telephone': receiveTelephone,
  recording1,
  recording2,
  refresh,
  regions,
  'remove-telephone': removeTelephone,
  'remove-user': removeUser,
  repeat,
  restore,
  right,
  right2,
  right3,
  rota,
  sale,
  sandwich,
  save,
  scan,
  'search-localization': searchLocalization,
  search,
  send,
  serial,
  server,
  share,
  'shield-off': shieldOff,
  'shield-tick': shieldTick,
  shield,
  'shopping-cart': shoppingCart,
  simcard,
  smartphone,
  speedometer,
  'star-solid': starSolid,
  star,
  stb,
  stop,
  sub,
  submit,
  'switch-horizontal1': switchHorizontal1,
  'switch-horizontal2': switchHorizontal2,
  'switch-vertical1': switchVertical1,
  'switch-vertical2': switchVertical2,
  'tag-division': tagDivision,
  tag,
  target,
  target3,
  tecnico,
  telephone,
  'thumbs-down': thumbsDown,
  'thumbs-up': thumbsUp,
  ticket,
  'time-telephone': timeTelephone,
  time,
  total,
  trash,
  trophy,
  tv,
  up,
  up2,
  up3,
  upload,
  'user-block': userBlock,
  'user-bottom': userBottom,
  'user-clock': userClock,
  'user-left': userLeft,
  'user-marker': userMarker,
  'user-minus': userMinus,
  'user-right': userRight,
  'user-search': userSearch,
  'user-top': userTop,
  user,
  users,
  vertical,
  'view-block': viewBlock,
  view,
  'volume-max': volumeMax,
  'volume-minus': volumeMinus,
  'volume-plus': volumePlus,
  'volume-x': volumeX,
  wallet,
  'watch-circle': watchCircle,
  whatsapp,
  wifi,
  'work-bag': workBag,
  working,
  'zap-off': zapOff,
  zap,
  'zoom-in': zoomIn,
  'zoom-out': zoomOut,
};

export type IconType = keyof typeof iconsPaths;
