name: 'Chromatic'

on: 
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  chromatic-deployment:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.19.0]
    steps:
      - uses: actions/checkout@v1
      - name: Install dependencies
        run: yarn
        # 👇 Adds Chromatic as a step in the workflow
      - name: Publish to Chromatic
        uses: chromaui/action@v1
        # Chromatic GitHub Action options
        with:
          # 👇 Chromatic projectToken, refer to the manage page to obtain it.
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
